version: "3.8"
services:
  emenu-backend:
    container_name: emenu-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file: .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./emenu-backend:/usr/src/app
    command: sh -c 'npm run start:dev'